# This is config file. Read as json in python file.
# This is fake config file to avoid expose personal information. 

# Change the name as config.yml
# Set your mattermost information here.

{
  "mattermost": {
    "webhook_url": "URL_OF_WEBHOOK",
    "bot_token": "BOT_TOKEN",
    "channel_id" : "CHANNEL_ID",
    "mm_api_url" : "URL_OF_YOUR_MATTERMOST/api/v4/posts"
  },
  "shotgrid": {
    "url" : "the url of shotgrid",
    "script_name" : "the script name",
    "api_key" : "the api key",
    "artist_name": "Artist name",
    "project_id" : "ID number of project",
    "project_name" : "The ShotGrid Project Name"
  }
}